version: "3"
services:
  galileo-orch:
    image: ghcr.io/euskaditech/galileo:main
    command: python3 orch/main.py
    networks:
      - cloudflared_tunnel
  galileo-001:
    image: ghcr.io/euskaditech/galileo:main
    volumes:
      - /mnt/storage/apps/galileo/001:/data
    networks:
      - cloudflared_tunnel
  pluto:
    image: ghcr.io/euskaditech/galileo:main
    command: python3 /mnt/storage/familia/Sistema/pluto/main.py
    volumes:
      - /mnt/storage/familia/Sistema/pluto:/mnt/storage/familia/Sistema/pluto
    ports:
      - 1129:1129
    networks:
      - cloudflared_tunnel
networks:
  cloudflared_tunnel:
    external: true
