version: '3'
services:
  naiel-fyi:
    image: ghcr.io/naielv/naiel.fyi:main # forcing update
    networks:
      - cloudflared_tunnel
  storage-ro:
    image: dceoy/nginx-autoindex:latest
    ports:
      - 8080:80
    volumes:
      - /mnt/storage:/var/lib/nginx/html:ro
    entrypoint:
      - /usr/sbin/nginx
    command:
      - -g
      - daemon off;
    networks:
      - cloudflared_tunnel
networks:
  cloudflared_tunnel:
    external: true
