version: '3.3'
services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PASSWORD: pepe
      DB_POSTGRESDB_USER: pepe
      DB_TYPE: postgresdb
      N8N_DIAGNOSTICS_ENABLED: 'false'
      N8N_PERSONALIZATION_ENABLED: 'false'
    ports:
     - 5678:5678
    volumes:
     - /mnt/storage/apps/artif/self-hosted-ai-starter-kit/n8n_storage:/home/node/.n8n
     - /mnt/storage/apps/artif/self-hosted-ai-starter-kit/shared:/data/shared
    networks:
     - demo
    logging:
      driver: journald
  postgres:
    image: postgres:16-alpine
    healthcheck:
      test:
       - CMD-SHELL
       - 'pg_isready -h localhost -U  -d '
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: n8n
      POSTGRES_PASSWORD: pepe
      POSTGRES_USER: pepe
    volumes:
     - /mnt/storage/apps/artif/self-hosted-ai-starter-kit/postgres_storage2:/var/lib/postgresql/data
    networks:
     - demo
    logging:
      driver: journald
  qdrant:
    image: qdrant/qdrant:latest
    ports:
     - 6333:6333
    volumes:
     - /mnt/storage/apps/artif/self-hosted-ai-starter-kit/qdrant_storage:/qdrant/storage
    networks:
     - demo
    logging:
      driver: journald
networks:
  demo:
    driver: overlay
