version: '3.3'
services:
  registry-mirror:
    image: registry:2
    ports:
     - 5000:5000
    volumes:
     - /mnt/storage/apps/registry/data:/var/lib/registry
     - /mnt/storage/apps/registry/config.yml:/etc/docker/registry/config.yml
    networks:
     - cloudflared_tunnel
    logging:
      driver: journald
networks:
  cloudflared_tunnel:
    external: true
