# This is a basic workflow to help you get started with Actions

name: Deploy Docker Stacks

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths:
      - "docker/**.yml"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Deploy docker on Nix-ES001
        # You may pin to the exact commit or the version.
        # uses: tiyee/action-ssh@b2d48d44e978ff09e0c37479a429a8374da6bb63
        uses: tiyee/action-ssh@v1.0.1
        with:
          # Command to execute on the remote server.
          command: cd /root/infra && git pull && python3 deploy-docker.py
          # Hostname or IP address of the server.
          host: nix-es001
          # Username for authentication.
          username: root
          # File  string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          privateKey: ${{ secrets.PRIVATE_KEY }}
                
