# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # (Not needed)
      # - uses: actions/checkout@v4
      - name: Deploy
        uses: tiyee/action-ssh@v1.0.1
        with:
          command: cd /root/infra && git pull && python3 deploy.py
          host: nix-es001
          username: root
          privateKey: ${{ secrets.PRIVATE_KEY }}